name: Containerd HTTP server test

concurrency:
  group: containerd-server-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  containerd_server:
    strategy:
      matrix:
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: ""
            crun: ""
            zh: "FALSE"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.9.1, Crun 1.4.5"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            zh: "FALSE"
            tag: "compat"
            variant: "compat"
          - name: "WasmEdge 0.10.0, Crun 1.5"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            zh: "FALSE"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge latest release, Crun master, ZH"
            latest: true
            wasmedge: ""
            crun: ""
            zh: "TRUE"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.9.1, Crun 1.4.5, ZH"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            zh: "TRUE"
            tag: "compat"
            variant: "compat"
          - name: "WasmEdge 0.10.0, Crun 1.5, ZH"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            zh: "TRUE"
            tag: "latest"
            variant: "compat-smart"
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install containerd and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
          ZH: ${{ matrix.zh }}
        run: |
          bash containerd/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION --zh=$ZH

      - name: Install containerd and crun (latest version)
        if: ${{ matrix.latest }}
        env:
          ZH: ${{ matrix.zh }}
        run: |
          bash containerd/install.sh --zh=$ZH

      - name: Run demo in containerd
        env:
          TAG: ${{ matrix.tag }}
          VARIANT: ${{ matrix.variant }}
        run: |
          bash containerd/http_server/http_server_application.sh --tag=$TAG --variant=$VARIANT

      - name: Display crun and wasmedge version
        run: |
          crun --version
          wasmedge --version
